###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum

from pydantic import BaseModel, ConfigDict

from typing_extensions import TypeAlias, Literal
from typing import Dict, Generic, List, Optional, TypeVar, Union

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class FaultLocation(BaseModel):
    name: Optional[str] = None
    machine: Optional[types.Machine] = None

class FaultMeasure(BaseModel):
    description: Optional[str] = None

class FaultReason(BaseModel):
    name: Optional[str] = None

class FaultReport(BaseModel):
    fault_location: Optional["FaultLocation"] = None
    fault_symptoms: List[str]
    fault_reason: List["FaultReason"]
    fault_measures: List["FaultMeasure"]
    resolution_status: Optional[types.ResolutionStatus] = None
