###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum

from pydantic import BaseModel, ConfigDict

from typing_extensions import TypeAlias, Literal
from typing import Dict, Generic, List, Optional, TypeVar, Union


T = TypeVar('T')
CheckName = TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, Generic[T,CheckName]):
    value: T
    checks: Dict[CheckName, Check]

def get_checks(checks: Dict[CheckName, Check]) -> List[Check]:
    return list(checks.values())

def all_succeeded(checks: Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))



class Machine(str, Enum):
    
    IBM3 = "IBM3"
    IBM4 = "IBM4"

class ResolutionStatus(str, Enum):
    
    Resolved = "Resolved"
    Unknown = "Unknown"

class FaultLocation(BaseModel):
    name: str
    machine: Optional["Machine"] = None

class FaultMeasure(BaseModel):
    description: str

class FaultReason(BaseModel):
    name: str

class FaultReport(BaseModel):
    fault_location: "FaultLocation"
    fault_symptoms: List[str]
    fault_reason: List["FaultReason"]
    fault_measures: List["FaultMeasure"]
    resolution_status: "ResolutionStatus"
