###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import typing
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder
from baml_py.type_builder import TypeBuilder as _TypeBuilder, ClassPropertyBuilder, ClassPropertyViewer, EnumValueViewer
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


class TypeBuilder(_TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["FaultLocation","FaultMeasure","FaultReason","FaultReport",]
        ), enums=set(
          ["Machine","ResolutionStatus",]
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)


    @property
    def FaultLocation(self) -> "FaultLocationAst":
        return FaultLocationAst(self)

    @property
    def FaultMeasure(self) -> "FaultMeasureAst":
        return FaultMeasureAst(self)

    @property
    def FaultReason(self) -> "FaultReasonAst":
        return FaultReasonAst(self)

    @property
    def FaultReport(self) -> "FaultReportAst":
        return FaultReportAst(self)





class FaultLocationAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("FaultLocation")
        self._properties: typing.Set[str] = set([ "name",  "machine", ])
        self._props = FaultLocationProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "FaultLocationProperties":
        return self._props


class FaultLocationViewer(FaultLocationAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class FaultLocationProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def name(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("name"))

    @property
    def machine(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("machine"))

    

class FaultMeasureAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("FaultMeasure")
        self._properties: typing.Set[str] = set([ "description", ])
        self._props = FaultMeasureProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "FaultMeasureProperties":
        return self._props


class FaultMeasureViewer(FaultMeasureAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class FaultMeasureProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def description(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("description"))

    

class FaultReasonAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("FaultReason")
        self._properties: typing.Set[str] = set([ "name", ])
        self._props = FaultReasonProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "FaultReasonProperties":
        return self._props


class FaultReasonViewer(FaultReasonAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class FaultReasonProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def name(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("name"))

    

class FaultReportAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("FaultReport")
        self._properties: typing.Set[str] = set([ "fault_location",  "fault_symptoms",  "fault_reason",  "fault_measures",  "resolution_status", ])
        self._props = FaultReportProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "FaultReportProperties":
        return self._props


class FaultReportViewer(FaultReportAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class FaultReportProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def fault_location(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("fault_location"))

    @property
    def fault_symptoms(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("fault_symptoms"))

    @property
    def fault_reason(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("fault_reason"))

    @property
    def fault_measures(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("fault_measures"))

    @property
    def resolution_status(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("resolution_status"))

    



class MachineAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("Machine")
        self._values: typing.Set[str] = set([ "IBM3",  "IBM4", ])
        self._vals = MachineValues(self._bldr, self._values)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "MachineValues":
        return self._vals


class MachineViewer(MachineAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    def list_values(self) -> typing.List[typing.Tuple[str, EnumValueViewer]]:
        return [(name, EnumValueViewer(self._bldr.value(name))) for name in self._values]


class MachineValues:
    def __init__(self, enum_bldr: EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values

    

    @property
    def IBM3(self) -> EnumValueViewer:
        return EnumValueViewer(self.__bldr.value("IBM3"))
    

    @property
    def IBM4(self) -> EnumValueViewer:
        return EnumValueViewer(self.__bldr.value("IBM4"))
    

    

class ResolutionStatusAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ResolutionStatus")
        self._values: typing.Set[str] = set([ "Resolved",  "Unknown", ])
        self._vals = ResolutionStatusValues(self._bldr, self._values)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ResolutionStatusValues":
        return self._vals


class ResolutionStatusViewer(ResolutionStatusAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    def list_values(self) -> typing.List[typing.Tuple[str, EnumValueViewer]]:
        return [(name, EnumValueViewer(self._bldr.value(name))) for name in self._values]


class ResolutionStatusValues:
    def __init__(self, enum_bldr: EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values

    

    @property
    def Resolved(self) -> EnumValueViewer:
        return EnumValueViewer(self.__bldr.value("Resolved"))
    

    @property
    def Unknown(self) -> EnumValueViewer:
        return EnumValueViewer(self.__bldr.value("Unknown"))
    

    


__all__ = ["TypeBuilder"]